"""add vendor and component to gate pass

Revision ID: 3e8a2a4f831b
Revises: d93064cc4382
Create Date: 2025-12-31 13:12:47.955236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8a2a4f831b'
down_revision: Union[str, Sequence[str], None] = 'd93064cc4382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gate_passes', sa.Column('vendor_name', sa.String(length=255), nullable=True))
    op.add_column('gate_passes', sa.Column('component_details', sa.String(length=255), nullable=True))
    op.create_index('idx_gate_pass_inspection', 'gate_passes', ['inspection_id'], unique=False)
    op.create_index('idx_gate_pass_store_status', 'gate_passes', ['store_status'], unique=False)
    # op.alter_column('inventory_transactions', 'transaction_type',
    #            existing_type=sa.VARCHAR(length=3),
    #            type_=sa.Enum('IN', 'OUT', 'REVERSAL', name='inventory_transaction_type'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('inventory_transactions', 'transaction_type',
    #            existing_type=sa.Enum('IN', 'OUT', 'REVERSAL', name='inventory_transaction_type'),
    #            type_=sa.VARCHAR(length=3),
    #            existing_nullable=False)
    op.drop_index('idx_gate_pass_store_status', table_name='gate_passes')
    op.drop_index('idx_gate_pass_inspection', table_name='gate_passes')
    op.drop_column('gate_passes', 'component_details')
    op.drop_column('gate_passes', 'vendor_name')
    # ### end Alembic commands ###
