"""sync material_receipt fields

Revision ID: 42050a0b2c26
Revises: 
Create Date: 2025-12-25 18:38:10.766002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42050a0b2c26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=50), nullable=True),
    sa.Column('entry_no', sa.String(length=50), nullable=True),
    sa.Column('mr_reference_no', sa.String(length=50), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('challan_no', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('purchase_number', sa.String(length=50), nullable=True),
    sa.Column('component_details', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_material_receipts_mr_number'), 'material_receipts', ['mr_number'], unique=True)
    op.create_index(op.f('ix_material_receipts_po_id'), 'material_receipts', ['po_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_vendor_id'), 'material_receipts', ['vendor_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('material_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mr_id'], ['material_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipt_lines_id'), 'material_receipt_lines', ['id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_item_id'), 'purchase_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_po_id'), 'purchase_order_lines', ['po_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_lines_po_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_item_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_material_receipt_lines_id'), table_name='material_receipt_lines')
    op.drop_table('material_receipt_lines')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_material_receipts_vendor_id'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_po_id'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_mr_number'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
