"""initial schema

Revision ID: 5a7a4c08ccea
Revises: 
Create Date: 2025-12-26 21:21:21.007616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7a4c08ccea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.String(length=10), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('total_worked_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PRESENT', 'IN_PROGRESS', 'COMPLETED', name='attendancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=50), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False),
    sa.Column('dispatch_type', sa.Enum('INTERNAL', 'EXTERNAL', name='dispatchtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'CANCELLED', name='dispatchstatus'), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('project_site', sa.String(length=100), nullable=True),
    sa.Column('issued_by', sa.String(length=100), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('gate_pass_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_dispatch_number'), 'dispatches', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_dispatches_id'), 'dispatches', ['id'], unique=False)
    op.create_table('gate_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_pass_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('store_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_pass_number')
    )
    op.create_index(op.f('ix_gate_passes_id'), 'gate_passes', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gate_pass_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gate_pass_id'),
    sa.UniqueConstraint('item_id', 'store_id', 'bin_id', 'gate_pass_id', name='uq_inventory_gate_pass')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_id'), 'inventory_items', ['item_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('material_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_number', sa.String(length=50), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=False),
    sa.Column('dispatch_status', sa.Enum('DRAFT', 'DISPATCHED', 'CANCELLED', name='dispatchstatus'), nullable=False),
    sa.Column('reference_type', sa.Enum('PO', 'SO', 'TRANSFER', name='referencetype'), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('receiver_name', sa.String(length=200), nullable=False),
    sa.Column('receiver_contact', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('driver_contact', sa.String(length=20), nullable=False),
    sa.Column('eway_bill_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_dispatches_dispatch_number'), 'material_dispatches', ['dispatch_number'], unique=True)
    op.create_index(op.f('ix_material_dispatches_id'), 'material_dispatches', ['id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('component_details', sa.String(length=1000), nullable=True),
    sa.Column('bill_no', sa.String(length=50), nullable=True),
    sa.Column('entry_no', sa.String(length=50), nullable=True),
    sa.Column('mr_reference_no', sa.String(length=50), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('vehicle_no', sa.String(length=50), nullable=True),
    sa.Column('challan_no', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_material_receipts_mr_number'), 'material_receipts', ['mr_number'], unique=True)
    op.create_index(op.f('ix_material_receipts_po_id'), 'material_receipts', ['po_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_vendor_id'), 'material_receipts', ['vendor_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plant_name', sa.String(length=255), nullable=False),
    sa.Column('in_charge_name', sa.String(length=255), nullable=False),
    sa.Column('in_charge_mobile', sa.String(length=20), nullable=False),
    sa.Column('in_charge_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=True)
    op.create_table('bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_no', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('component_details', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bins_bin_no'), 'bins', ['bin_no'], unique=False)
    op.create_index(op.f('ix_bins_id'), 'bins', ['id'], unique=False)
    op.create_table('dispatch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('dispatch_qty', sa.Float(), nullable=False),
    sa.Column('batch_lot', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_items_id'), 'dispatch_items', ['id'], unique=False)
    op.create_table('gate_pass_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate_pass_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gate_pass_id'], ['gate_passes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_dispatch_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_dispatched', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['material_dispatches.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_dispatch_line_items_id'), 'material_dispatch_line_items', ['id'], unique=False)
    op.create_table('material_receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.Integer(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mr_id'], ['material_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipt_lines_id'), 'material_receipt_lines', ['id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_item_id'), 'purchase_order_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_po_id'), 'purchase_order_lines', ['po_id'], unique=False)
    op.create_table('quality_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=True),
    sa.Column('inspected_by', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['mr_id'], ['material_receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_id')
    )
    op.create_index(op.f('ix_quality_inspections_id'), 'quality_inspections', ['id'], unique=False)
    op.create_table('quality_inspection_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('mr_line_id', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['quality_inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_inspection_lines_id'), 'quality_inspection_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_quality_inspection_lines_id'), table_name='quality_inspection_lines')
    # op.drop_table('quality_inspection_lines')
    # op.drop_index(op.f('ix_quality_inspections_id'), table_name='quality_inspections')
    # op.drop_table('quality_inspections')
    # op.drop_index(op.f('ix_purchase_order_lines_po_id'), table_name='purchase_order_lines')
    # op.drop_index(op.f('ix_purchase_order_lines_item_id'), table_name='purchase_order_lines')
    # op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    # op.drop_table('purchase_order_lines')
    # op.drop_index(op.f('ix_material_receipt_lines_id'), table_name='material_receipt_lines')
    # op.drop_table('material_receipt_lines')
    # op.drop_index(op.f('ix_material_dispatch_line_items_id'), table_name='material_dispatch_line_items')
    # op.drop_table('material_dispatch_line_items')
    # op.drop_table('gate_pass_items')
    # op.drop_index(op.f('ix_dispatch_items_id'), table_name='dispatch_items')
    # op.drop_table('dispatch_items')
    # op.drop_index(op.f('ix_bins_id'), table_name='bins')
    # op.drop_index(op.f('ix_bins_bin_no'), table_name='bins')
    # op.drop_table('bins')
    # op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    # op.drop_index(op.f('ix_stores_id'), table_name='stores')
    # op.drop_table('stores')
    # op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    # op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    # op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    # op.drop_table('purchase_orders')
    # op.drop_index(op.f('ix_material_receipts_vendor_id'), table_name='material_receipts')
    # op.drop_index(op.f('ix_material_receipts_po_id'), table_name='material_receipts')
    # op.drop_index(op.f('ix_material_receipts_mr_number'), table_name='material_receipts')
    # op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    # op.drop_table('material_receipts')
    # op.drop_index(op.f('ix_material_dispatches_id'), table_name='material_dispatches')
    # op.drop_index(op.f('ix_material_dispatches_dispatch_number'), table_name='material_dispatches')
    # op.drop_table('material_dispatches')
    # op.drop_index(op.f('ix_items_name'), table_name='items')
    # op.drop_index(op.f('ix_items_id'), table_name='items')
    # op.drop_index(op.f('ix_items_code'), table_name='items')
    # op.drop_table('items')
    # op.drop_index(op.f('ix_inventory_items_item_id'), table_name='inventory_items')
    # op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    # op.drop_table('inventory_items')
    # op.drop_index(op.f('ix_gate_passes_id'), table_name='gate_passes')
    # op.drop_table('gate_passes')
    # op.drop_index(op.f('ix_dispatches_id'), table_name='dispatches')
    # op.drop_index(op.f('ix_dispatches_dispatch_number'), table_name='dispatches')
    # op.drop_table('dispatches')
    # op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    # op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    # op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    # op.drop_table('attendance')
    # ### end Alembic commands ###
