"""add announcements module

Revision ID: 6700031b60ae
Revises: 6073224015eb
Create Date: 2025-12-26 15:26:59.954120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6700031b60ae'
down_revision: Union[str, Sequence[str], None] = '6073224015eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_receipts', 'vendor_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('material_receipts', 'component_details',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_column('material_receipts', 'quantity')
    op.drop_column('material_receipts', 'purchase_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_receipts', sa.Column('purchase_number', sa.VARCHAR(length=50), nullable=True))
    op.add_column('material_receipts', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.alter_column('material_receipts', 'component_details',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('material_receipts', 'vendor_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
